<?php echo $this->doctype(); ?>

<html lang="en">

<head>

    <title>Chris Kankiewicz &bull; Web Application Developer</title>
    <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

    <!-- META -->
    <?php $this->headMeta()->setCharset('utf-8'); ?>
    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <?php echo $this->headMeta(); ?>

    <!-- STYLES / FONTS -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/font-awesome.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css'); ?>

    <?php $this->headLink()->appendStylesheet('//fonts.googleapis.com/css?family=Arvo|Oxygen:300,400,700'); ?>

    <?php echo $this->headLink(); ?>

    <!-- SCRIPTS -->
    <?php $this->headScript()->appendFile('//code.jquery.com/jquery-2.1.1.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js'); ?>
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/chriskankiewicz.js'); ?>

    <?php echo $this->headScript(); ?>

</head>

<?php $children = $this->viewModel()->getCurrent()->getChildren(); $child = $children[0]; ?>

<body>

    <div class="header-bg">

        <div class="site-header">
            <div class="container">

                <a href="/" class="site-title clearfix">

                    <span class="title-img">
                        <?php echo $this->gravatar('Chris@ChrisKankiewicz.com')->setImgSize(120)->setAttribs(array('class' => 'img-circle img-responsive')); ?>
                    </span>

                    <span class="title-text">
                        <h1>Chris Kankiewicz</h1>
                    </span>

                </a>

                <button class="navbar-toggle" data-toggle="collapse" data-target="#nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <ul class="site-nav">

                    <li>
                        <a href="/">Home</a>
                    </li>

                    <li>
                        <a href="http://blog.chriskankiewicz.com">Blog</a>
                    </li>

                </ul>

            </div>
        </div>

    </div>

    <div class="sub-text navbar navbar-static-top navbar-inverse">
        <div class="container">

                <div class="quip navbar-text">
                    Full Stack Web &amp; Application Developer &bull; Mesa, Arizona
                </div>

                <div class="social-nav navbar-right">

                    <div class="navbar-text">Follow:</div>

                    <ul class="nav navbar-nav">

                        <li>
                            <a href="http://goo.gl/3Wur6L" class="follow-github" title="GitHub" rel="tooltip" data-placement="bottom">
                                <i class="fa fa-github fa-lg"></i>
                            </a>
                        </li>

                        <li>
                            <a href="http://goo.gl/SWK9Cd" class="follow-linkedin" title="Linkedin" rel="tooltip" data-placement="bottom">
                                <i class="fa fa-linkedin fa-lg"></i>
                            </a>
                        </li>

                        <li>
                            <a href="http://goo.gl/KTHmpb" class="follow-google-plus" title="Google+" rel="tooltip" data-placement="bottom">
                                <i class="fa fa-google-plus fa-lg"></i>
                            </a>
                        </li>

                        <li>
                            <a href="http://goo.gl/xpVJzg" class="follow-twitter" title="Twitter" rel="tooltip" data-placement="bottom">
                                <i class="fa fa-twitter fa-lg"></i>
                            </a>
                        </li>

                        <li>
                            <a href="http://goo.gl/n2RZpm" class="follow-keybase" title="Keybase" rel="tooltip" data-placement="bottom">
                                <i class="fa fa-key fa-lg"></i>
                            </a>
                        </li>

                        <?php /* <li>
                            <a href="http://goo.gl/lDpwxg" class="follow-rss" title="Blog" rel="tooltip">
                                <i class="fa fa-rss fa-lg"></i>
                            </a>
                        </li> */ ?>

                    </ul>

                </div>

            </div>
        </div>
    </div>

    <div class="content-area">

        <?php echo $this->content; ?>

    </div>

    <div class="site-footer">
        <div class="container">
            623-252-6855 &nbsp;&bull;&nbsp;
            <a href="mailto:Chris@ChrisKankiewicz.com">Chris@ChrisKankiewicz.com</a>
            <br><br>
            &copy; <?php echo date('Y'); ?> <a href="/">Chris Kankiewicz</a>
        </div>
    </div>

    <?php echo $this->inlineScript(); ?>

</body>

</html>
