<div class="container">

    <div class="card">
        <div class="intro-card card-body">
            <p class="lead text-justify">Self taught web developer and designer with real world experience and a desire to
            learn. Personal strengths include advanced troubleshooting and problem solving
            skills, the capacity to acquire and apply new knowledge quickly and the ability to
            work efficiently in a team centric environment.</p>
        </div>
    </div>


    <div class="card">

        <h2 class="card-title"><i class="fa fa-briefcase fa-fw"></i> Experience</h2>

        <div class="card-body">

            <div class="row">

                <div class="col-sm-12 col-md-6">

                    <h3>
                        IO Data Center<br>
                        <small>Software Development Engineer (June 2014 - Present)</small>
                    </h3>
                    <ul>
                        <li>Managed Linux-backed, Open Stack cloud infrustructure.</li>
                        <li>Developed and maintained automated, continuous integration systems.</li>
                    </ul>

                </div>

                <div class="col-sm-12 col-md-6">

                    <h3>
                        Arizona State University<br>
                        <small>Web Application Developer (April 2011 - June 2014)</small>
                    </h3>
                    <ul>
                        <li>Developed, managed and maintained complex PHP based web applications.</li>
                        <li>Conceptualized, designed and implemented detailed site layouts.</li>
                    </ul>

                </div>


            </div>

            <div class="row">

                <div class="col-sm-12 col-md-6">

                    <h3>
                        Southwest Medical &amp; Rehab<br>
                        <small>Web Developer / Designer (March 2009 - April 2011)</small>
                    </h3>
                    <ul>
                        <li>Conceptualized, designed, implemented and tested detailed e-commerce site layouts.</li>
                        <li>Performed search engine optimizations to enhance traffic to all sites.</li>
                    </ul>

                </div>

                <div class="col-sm-12 col-md-6">

                    <h3>
                        PetSmart Store Support Group<br>
                        <small>Solution Center Technician (February 2008 - March 2009)</small>
                    </h3>
                    <ul>
                        <li>Provided over-the-phone technical support to store and corporate employees.</li>
                        <li>Performed advanced troubleshooting on store servers, registers, and workstations.</li>
                    </ul>

                </div>


            </div>

            <?php /* <div class="row">

                <div class="col-sm-12 col-md-6">

                    <h3>
                        Jannenga Enterprises, LLC<br>
                        <small>Web and Graphics Designer (May 2006 - October 2007)</small>
                    </h3>
                    <ul>
                        <li>Conceptualized, designed and coordinated the implementation of detailed web pages and graphics.</li>
                        <li>Performed routine and advanced maintenance on PC systems, networks, and other digital equipment.</li>
                    </ul>

                </div>

            </div> */ ?>

        </div>

    </div>


    <div class="card">

        <h2 class="card-title"><i class="fa fa-book fa-fw"></i> Education</h2>

        <div class="card-body">

            <div class="row">

                <div class="col-sm-12 col-md-6">

                    <h3>DeVry University<br><small>July 2005 - February 2008</small></h3>
                    <ul>
                        <li>Bachelor's of Science Degree in Network and Communication Management</li>
                    </ul>

                </div>

                <div class="col-sm-12 col-md-6">

                    <h3>Shadow Mountain High School<br><small>Class of 2005</small></h3>
                    <ul>
                        <li>High school diploma</li>
                        <li>National Honor Society</li>
                    </ul>

                </div>

            </div>

        </div>

    </div>


    <div class="card">

        <h2 class="card-title"><i class="fa fa-lightbulb-o fa-fw"></i> Qualifications</h2>

        <div class="card-body">

            <div class="row">
                <div class="col-md-12">

                    <div class="row">

                        <div class="col-md-4">
                            <h3>Web Development</h3>
                            <ul class="list-inline">
                                <li class="label label-primary">HTML</li>
                                <li class="label label-primary">CSS</li>
                                <li class="label label-warning">JavaScript</li>
                                <li class="label label-warning">jQuery</li>
                                <li class="label label-danger">PHP</li>
                                <li class="label label-danger">MySQL</li>
                                <li class="label label-success">SEO</li>
                                <li class="label label-info">Git</li>
                                <li class="label label-info">Composer</li>
                            </ul>
                        </div>

                        <div class="col-md-4">
                            <h3>Software / Frameworks</h3>
                            <ul class="list-inline">
                                <li class="label label-success">Zend Framework</li>
                                <li class="label label-success">CakePHP</li>
                                <li class="label label-success">CodeIgniter</li>
                                <li class="label label-info">Wordpress</li>
                                <li class="label label-info">Drupal</li>
                                <li class="label label-warning">Vagrant</li>
                                <li class="label label-warning">SaltStack</li>
                                <li class="label label-primary">Photoshop</li>
                            </ul>
                        </div>

                        <div class="col-md-4">
                            <h3>System Administration</h3>
                            <ul class="list-inline">
                                <li class="label label-success">Windows</li>
                                <li class="label label-success">Linux</li>
                                <li class="label label-danger">Nginx</li>
                                <li class="label label-danger">Apache</li>
                                <li class="label label-primary">PC Hardware</li>
                                <li class="label label-info">Networking</li>
                                <li class="label label-info">Cisco IOS</li>
                            </ul>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>


    <div class="card">

        <h2 class="card-title"><i class="fa fa-trophy fa-fw"></i> Achievements</h2>

        <div class="card-body">

            <div class="row">

                <div class="col-sm-12 col-md-6">

                    <h3>Projects</h3>
                    <ul>
                        <li><a href="http://www.ubergallery.net">UberGallery</a></li>
                        <li><a href="http://www.directorylister.com">Directory Lister</a></li>
                        <li><a href="https://github.com/PHLAK/strgen">StrGen</a></li>
                        <li><a href="https://github.com/PHLAK/colorizer">Colorizer</a></li>
                        <li><a href="http://phlak.github.io/jColorClock">jColorClock</a></li>
                    </ul>

                </div>

                <div class="col-sm-12 col-md-6">

                    <h3>Miscellaneous</h3>
                    <ul>
                        <li>Award: Eagle Scout</li>
                        <li><a href="https://www.phx2600.org">PHX2600</a> Member &amp; Web Master</li>
                        <li>Regular attendee at <a href="http://defcon.org/">DEF CON</a></li>
                        <li><a href="https://gist.github.com/PHLAK">My Gists</a></li>
                    </ul>

                </div>

            </div>

        </div>

    </div>

    <div class="card map-card hidden-xs">

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

        <script type="text/javascript">

            function getGeocode(address) {

                // Initialize location object
                var location = new Object();

                // Initialize geocoder object
                var geocoder = new google.maps.Geocoder();

                geocoder.geocode({ 'address': address }, function(results, status) {

                    if (status == google.maps.GeocoderStatus.OK) {

                        location['lat'] = results[0].geometry.location.lat();
                        location['lng'] = results[0].geometry.location.lng();

                    }

                });

                return location;

            }

            // Get location info for Phoenix, AZ
            var geo = getGeocode('Phoenix, AZ');

            // Initialize the Google map on load
            google.maps.event.addDomListener(window, 'load', function() {

                // Initialize the Google map
                map = new google.maps.Map(document.getElementById('map-canvas'), {
                    center: new google.maps.LatLng(geo.lat + 0.0196729, geo.lng),
                    zoom: 10,
                    disableDefaultUI: true,
                    scrollwheel: false,
                    zoomControl: true
                });

                // Place a marker
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(geo.lat, geo.lng),
                    map: map,
                    draggable: false
                });

            });

        </script>

        <div id="map-canvas"></div>

    </div>

</div>
